import { useRef, useState, type FormEvent } from 'react';
import { AlertCircle, Download, FileSpreadsheet, Save, Trash2, Upload } from 'lucide-react';
import { downloadCSV } from './api';
import { type ClassData, type MarkRow, letters, mean } from './types';

export function FormError({ error }: { error: string }) { return error ? <div className="form-error" role="alert"><AlertCircle size={17}/><span>{error}</span></div> : null; }

export function StudentForm({ data, row, busy, error, onSubmit, onDelete, onClose }: {
  data: ClassData; row?: MarkRow; busy: boolean; error: string;
  onSubmit: (row: MarkRow) => void; onDelete: () => void; onClose: () => void;
}) {
  const [name, setName] = useState(row?.Name ?? '');
  const [id, setId] = useState(row?.['Student ID'] ?? '');
  const [marks, setMarks] = useState<Record<string, string>>(() => Object.fromEntries(data.subjects.map(s => [s, row ? String(row[s]) : ''])));
  const average = data.subjects.every(s => marks[s] !== '') ? mean(data.subjects.map(s => Number(marks[s]))) : null;
  const submit = (e: FormEvent) => { e.preventDefault(); onSubmit({ 'Student ID': id.trim(), Name: name.trim(), ...Object.fromEntries(data.subjects.map(s => [s, Number(marks[s])])) }); };
  return <form onSubmit={submit}><fieldset disabled={busy}><div className="form-grid"><label>Student name<input required maxLength={200} value={name} autoFocus onChange={e => setName(e.target.value)} placeholder="e.g. Amina Yusuf"/></label><label>Student ID<input required maxLength={100} value={id} onChange={e => setId(e.target.value)} placeholder="e.g. S011"/></label></div><div className="form-section-title"><h3>Subject marks</h3><span>Out of 100</span></div><div className="form-grid">{data.subjects.map(subject => <label key={subject}>{subject}<input type="number" min="0" max="100" step="any" required value={marks[subject]} onChange={e => setMarks({ ...marks, [subject]: e.target.value })} placeholder="Enter mark"/></label>)}</div><div className="preview-line"><span>Average preview</span><strong>{average === null ? 'Enter all marks' : `${average.toFixed(2)}%`}</strong></div><FormError error={error}/><div className="modal-actions">{row && <button type="button" className="text-button danger" onClick={onDelete}><Trash2 size={15}/>Delete student</button>}<span className="spacer"/><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" type="submit"><Save size={16}/>{busy ? 'Saving…' : row ? 'Save changes' : 'Add student'}</button></div></fieldset></form>;
}

export function NewClassForm({ busy, error, onSubmit, onClose }: { busy: boolean; error: string; onSubmit: (name: string, term: string, subjects: string[]) => void; onClose: () => void }) {
  const [name, setName] = useState(''); const [term, setTerm] = useState(''); const [subjects, setSubjects] = useState('Mathematics, English, Science');
  return <form onSubmit={e => { e.preventDefault(); onSubmit(name, term, subjects.split(',').map(s => s.trim())); }}><fieldset disabled={busy}><label>Class name<input autoFocus required maxLength={100} value={name} onChange={e => setName(e.target.value)} placeholder="e.g. SS1 A"/></label><label>Term or assessment<input required maxLength={100} value={term} onChange={e => setTerm(e.target.value)} placeholder="e.g. First term · 2026/27"/></label><label>Subjects<textarea aria-label="Subjects" aria-describedby="subjects-help" required value={subjects} onChange={e => setSubjects(e.target.value)} rows={3}/><small id="subjects-help">Separate subject names with commas. Each subject counts equally.</small></label><FormError error={error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" type="submit">{busy ? 'Creating…' : 'Create class'}</button></div></fieldset></form>;
}

export function ImportForm({ data, busy, error, onSubmit, onClose }: { data: ClassData; busy: boolean; error: string; onSubmit: (csv: string, replace: boolean) => void; onClose: () => void }) {
  const [csv, setCsv] = useState(''); const [filename, setFilename] = useState(''); const [replace, setReplace] = useState(false); const [fileError, setFileError] = useState(''); const [reading, setReading] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const readFile = async (file?: File) => {
    if (!file) return;
    setReading(true); setCsv(''); setFilename(''); setFileError('');
    try {
      if (file.size > 2000000) throw new Error('Choose a CSV file smaller than 2 MB.');
      const text = new TextDecoder('utf-8', { fatal: true }).decode(await file.arrayBuffer());
      setCsv(text); setFilename(file.name);
    } catch (e) { setFileError(e instanceof Error ? e.message : 'Could not read this file. Save it as UTF-8 CSV.'); }
    finally { setReading(false); }
  };
  return <form onSubmit={e => { e.preventDefault(); onSubmit(csv, replace); }}><fieldset disabled={busy || reading}><button className={`upload-area ${filename ? 'has-file' : ''}`} type="button" onClick={() => input.current?.click()}><span className="upload-icon"><FileSpreadsheet size={28}/></span><strong>{reading ? 'Reading file…' : filename || 'Choose a CSV file'}</strong><span>{filename ? 'Click to choose a different file' : 'UTF-8 CSV · up to 2 MB'}</span></button><input className="sr-only" ref={input} aria-label="CSV file" type="file" accept=".csv,text/csv" onChange={e => { void readFile(e.target.files?.[0]); e.target.value = ''; }}/><div className="import-columns"><strong>Required columns</strong><p>{['Student ID', 'Name', ...data.subjects].join(', ')}</p><button type="button" className="text-button" onClick={() => downloadCSV([], ['Student ID', 'Name', ...data.subjects], 'marks_template.csv')}><Download size={15}/>Download empty template</button></div><label className="checkbox-label"><input type="checkbox" checked={replace} onChange={e => setReplace(e.target.checked)}/><span>Replace existing students<small>{replace ? `This will replace all ${data.records.length} students in this class with the imported file.` : 'Students will be added. Existing IDs are rejected to prevent duplicates.'}</small></span></label><FormError error={fileError || error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" type="submit" disabled={!csv}><Upload size={16}/>{busy ? 'Importing…' : replace ? 'Replace and import' : 'Import students'}</button></div></fieldset></form>;
}

export function Settings({ data, busy, onSave }: { data: ClassData; busy: boolean; onSave: (scale: Record<string, number>, passMark: number) => Promise<void> }) {
  const [scale, setScale] = useState(data.scale); const [pass, setPass] = useState(data.pass_mark); const [error, setError] = useState('');
  const dirty = pass !== data.pass_mark || letters.slice(0, 5).some(g => scale[g] !== data.scale[g]);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); try { await onSave(scale, pass); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save.'); } };
  return <div className="settings-layout"><section className="panel settings-panel"><div className="panel-heading"><div><h2>Grading scale</h2><p>Changes apply to every student in {data.name}.</p></div><span className="count-tag">0–100</span></div><form onSubmit={e => void submit(e)}><fieldset disabled={busy}><div className="grade-settings">{letters.slice(0, 5).map((g, i) => <label key={g}><span className="grade-setting-label"><span className={`grade-badge grade-${g}`}>{g}</span><span>Grade {g}<small>{i === 0 ? 'Highest grade' : `Below grade ${letters[i - 1]}`}</small></span></span><span className="boundary-input"><input aria-label={`Minimum for ${g}`} required type="number" min="0" max="100" step="any" value={Number.isNaN(scale[g]) ? '' : scale[g]} onChange={e => setScale({ ...scale, [g]: e.target.value === '' ? NaN : Number(e.target.value) })}/><span>% and above</span></span></label>)}</div><div className="pass-setting"><label>Overall pass mark<small>Students pass when their average meets this value.</small></label><div className="boundary-input"><input aria-label="Pass mark" type="number" min="0" max="100" step="any" required value={Number.isNaN(pass) ? '' : pass} onChange={e => setPass(e.target.value === '' ? NaN : Number(e.target.value))}/><span>%</span></div></div><FormError error={error}/><div className="settings-footer"><button className="text-button" type="button" onClick={() => { setScale({ A: 70, B: 60, C: 50, D: 45, E: 40 }); setPass(40); }}>Use default scale</button><button className="button primary" disabled={!dirty} type="submit"><Save size={16}/>{busy ? 'Saving…' : 'Save grading rules'}</button></div></fieldset></form></section><aside><section className="insight-card"><h3>Consistent, clear results.</h3><p>Grade boundaries must descend strictly from A to E. Marks below the E boundary receive F.</p><p>Grades and rankings use exact averages. Rounding only affects what you see on screen.</p></section><section className="panel report-rules"><span className="eyebrow">CLASS DETAILS</span><p>Class <strong>{data.name}</strong></p><p>Assessment <strong>{data.term}</strong></p><p>Subjects <strong>{data.subjects.length}</strong></p><small>Create a new class for a different term or subject set. Each class keeps its own records and grading rules.</small></section></aside></div>;
}
