import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, BarChart3, BookOpen, CheckCircle2, CircleHelp, ClipboardList, Database, GraduationCap, LayoutDashboard, LoaderCircle, LogOut, Maximize2, Menu, Minimize2, Monitor, RefreshCw, Settings, ShieldCheck, Users, X } from 'lucide-react';
import { ApiError, request } from './api';
import { Analytics } from './SchoolCharts';
import { ClassForm, ScoresForm, SessionForm, StudentForm, type StudentInput } from './SchoolForms';
import { Dashboard, Report, Results, SchoolSettings, Students } from './SchoolPages';
import { ErrorMessage, Logo, SchoolModal } from './SchoolUI';
import { type ResultEntry, type SchoolPage, type SchoolResult, type Selection, type Student, type User, type Workspace, queryFor } from './school-types';

const navigation = [
  { page: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, subtitle: 'School totals and an overview of class performance.' },
  { page: 'students', label: 'Students', icon: Users, subtitle: 'Register students and view their results.' },
  { page: 'results', label: 'Results', icon: ClipboardList, subtitle: 'Enter marks. Let Python calculate the results.' },
  { page: 'analytics', label: 'Analytics', icon: BarChart3, subtitle: 'Compare subjects, students, genders and terms.' },
  { page: 'reports', label: 'Student Report', icon: BookOpen, subtitle: 'A clear, professional school report sheet.' },
  { page: 'settings', label: 'Settings', icon: Settings, subtitle: 'Manage grading rules, classes and academic sessions.' },
] as const;
const messageOf = (e: unknown) => e instanceof Error ? e.message : 'Something went wrong. Please try again.';
type Dialog = 'student' | 'scores' | 'class' | 'session' | 'architecture' | null;

function Login({ onLogin, error: connectionError, retry }: { onLogin: (username: string, password: string) => Promise<void>; error: string; retry: () => void }) {
  const [username, setUsername] = useState('teacher'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const login = async (demo = false) => { setBusy(true); setError(''); try { await onLogin(demo ? 'teacher' : username, demo ? 'BrightFuture2026!' : password); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-navy px-5 py-10"><div className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl sm:p-10"><div className="flex flex-col items-center text-center"><Logo className="h-24 w-20"/><h1 className="mt-5 text-2xl font-extrabold text-navy">Bright Future School</h1><p className="mt-2 text-base font-semibold text-slate-500">SmartSchool Results Analytics System</p><span className="mt-5 rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">SIMPLE SCHOOL PRESENTATION</span></div><button disabled={busy} className="btn mt-7 w-full py-3.5 text-base" onClick={() => void login(true)}>{busy ? <LoaderCircle size={19} className="animate-spin"/> : <GraduationCap size={21}/>}Open presentation demo<ArrowRight size={19}/></button><p className="mt-3 text-center text-sm text-slate-500">One click. Fictional students. Ready to demonstrate.</p><details className="mt-6 border-t border-slate-200 pt-5"><summary className="cursor-pointer text-center text-sm font-semibold text-slate-500">Or sign in as a teacher</summary><form className="mt-4 space-y-4" onSubmit={e => { e.preventDefault(); void login(); }}><fieldset disabled={busy} className="space-y-4"><label className="form-label">Username<input required autoComplete="username" value={username} onChange={e => setUsername(e.target.value)}/></label><label className="form-label">Password<input required type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)}/></label><button className="btn w-full" type="submit">Sign in</button></fieldset></form></details><ErrorMessage error={error || connectionError}/>{connectionError && <button className="btn-light mt-4 w-full" onClick={retry}><RefreshCw size={17}/>Check connection</button>}<p className="mt-7 text-center text-xs text-slate-400">React · Python + FastAPI · SQLite</p></div></div>;
}

function Architecture() {
  return <div><p className="mb-6 text-sm leading-relaxed text-slate-500">The system has three main parts. Marks travel from the interface to Python, then into the database.</p><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><Monitor className="mb-3 text-blue-700"/><h3 className="font-bold text-navy">1. React frontend</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Displays pages, forms and charts. Tailwind CSS styles the interface. Recharts draws the analytics.</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><GraduationCap className="mb-3 text-amber-700"/><h3 className="font-bold text-navy">2. Python + FastAPI</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Validates marks, calculates totals, averages, grades, remarks and positions, and authenticates the teacher.</p></div></div><div className="my-3 flex justify-center text-slate-400"><ArrowDown size={24}/></div><div className="rounded-2xl border border-teal-200 bg-teal-50 p-5 text-center"><Database className="mx-auto mb-3 text-teal-700"/><h3 className="font-bold text-navy">3. SQLite database</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">Stores students, classes, subjects, results, academic sessions and users.</p></div><div className="mt-6 rounded-xl bg-slate-100 p-4 text-center text-sm font-semibold leading-loose text-navy">Enter marks → Python calculates → SQLite saves → React displays</div></div>;
}

export default function SchoolApp() {
  const [user, setUser] = useState<User | null>(null); const [checking, setChecking] = useState(true); const [authTick, setAuthTick] = useState(0);
  const [selection, setSelection] = useState<Selection>({ class_id: 1, session_id: 1, term: 'First Term' });
  const [data, setData] = useState<Workspace | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [tick, setTick] = useState(0);
  const [page, setPage] = useState<SchoolPage>('dashboard'); const [dialog, setDialog] = useState<Dialog>(null); const [student, setStudent] = useState<Student>(); const [scoreRow, setScoreRow] = useState<SchoolResult>();
  const [busy, setBusy] = useState(false); const [formError, setFormError] = useState(''); const [dirty, setDirty] = useState(false); const [chosenId, setChosenId] = useState<number>(); const [grade, setGrade] = useState('');
  const [mobileMenu, setMobileMenu] = useState(false); const [presenting, setPresenting] = useState(false); const [toast, setToast] = useState('');
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  useEffect(() => { const controller = new AbortController(); setChecking(true); request<User>('/school/me', { signal: controller.signal }).then(setUser).catch(e => { if (!controller.signal.aborted && !(e instanceof ApiError && e.status === 401)) setLoadError(messageOf(e)); }).finally(() => { if (!controller.signal.aborted) setChecking(false); }); return () => controller.abort(); }, [authTick]);
  useEffect(() => {
    if (!user) return;
    const controller = new AbortController(); setLoading(true); setLoadError('');
    request<Workspace>(`/school/workspace?${queryFor(selection)}`, { signal: controller.signal }).then(setData).catch(e => {
      if (!controller.signal.aborted) { if (e instanceof ApiError && e.status === 401) setUser(null); else setLoadError(messageOf(e)); }
    }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [user, selection.class_id, selection.session_id, selection.term, tick]);
  useEffect(() => { const changed = () => setPresenting(!!document.fullscreenElement); document.addEventListener('fullscreenchange', changed); return () => document.removeEventListener('fullscreenchange', changed); }, []);
  useEffect(() => () => clearTimeout(timer.current), []);

  const notify = (text: string) => { setToast(text); clearTimeout(timer.current); timer.current = setTimeout(() => setToast(''), 5000); };
  const guard = () => !dirty || window.confirm('You have unsaved marks. Discard these changes?');
  const navigate = (next: SchoolPage) => { if (next === page) { setMobileMenu(false); return; } if (guard()) { setDirty(false); setPage(next); setMobileMenu(false); } };
  const changeSelection = (next: Selection) => { if (guard()) { setDirty(false); setData(null); setSelection(next); setChosenId(undefined); setGrade(''); } };
  const open = (kind: Dialog) => { setFormError(''); setDialog(kind); };
  const report = (id: number) => { if (guard()) { setDirty(false); setChosenId(id); setPage('reports'); setMobileMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); } };
  const refresh = () => { if (guard()) { setDirty(false); setDialog(null); setTick(t => t + 1); } };
  const perform = async (path: string, body: unknown, note: string, method = 'PUT') => {
    setBusy(true); setFormError('');
    try { const result = await request<{ id?: number }>(`/school${path}`, { method, body: JSON.stringify(body) }); const next = await request<Workspace>(`/school/workspace?${queryFor(selection)}`); setData(next); setDirty(false); setDialog(null); notify(note); return result; }
    catch (e) { setFormError(messageOf(e)); if (e instanceof ApiError && e.status === 401) { setUser(null); setDialog(null); } throw e; }
    finally { setBusy(false); }
  };
  const saveStudent = async (values: StudentInput) => { try { await perform(student ? `/students/${student.id}` : '/students', values, student ? 'Student details saved.' : 'Student registered. Enter marks on the Results page.', student ? 'PUT' : 'POST'); if (values.class_id !== selection.class_id || values.session_id !== selection.session_id) changeSelection({ ...selection, class_id: values.class_id, session_id: values.session_id }); } catch { /* Shown in the form. */ } };
  const saveMarks = async (entries: ResultEntry[]) => { if (data) await perform(`/results?${queryFor(selection)}`, { revision: data.assessment.revision, entries }, 'Results saved. Totals, grades and positions recalculated.'); };
  const fullScreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); } catch { notify('Use your browser’s full-screen option to present.'); } };
  const chosen = data?.results.find(r => r.id === chosenId) || data?.results.find(r => r.student_code === 'BFS001') || data?.results[0];
  const current = navigation.find(n => n.page === page)!;

  if (checking) return <div className="flex min-h-screen items-center justify-center gap-3 text-navy"><LoaderCircle className="animate-spin"/>Opening SmartSchool…</div>;
  if (!user) return <Login error={loadError} retry={() => { setLoadError(''); setAuthTick(v => v + 1); }} onLogin={async (username, password) => { const logged = await request<User>('/school/login', { method: 'POST', body: JSON.stringify({ username, password }) }); setLoadError(''); setUser(logged); }}/>;

  return <div className={presenting ? 'presentation-view' : ''}>
    {mobileMenu && <button className="fixed inset-0 z-30 bg-navy/50 lg:hidden" aria-label="Close navigation" onClick={() => setMobileMenu(false)}/>}
    <aside className={`school-sidebar fixed inset-y-0 left-0 z-40 flex w-60 flex-col bg-navy px-4 py-6 text-white lg:translate-x-0 ${mobileMenu ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center gap-3 px-2"><Logo className="h-15 w-13"/><div><strong className="text-xl font-bold tracking-tight">SmartSchool</strong><p className="mt-1 text-xs text-blue-200">Results Analytics System</p></div></div><div className="mx-2 mt-6 border-t border-white/10 pt-5"><p className="text-sm font-semibold">Bright Future School</p><p className="mt-1 text-xs text-blue-200">Learn. Lead. Excel.</p></div><p className="mt-7 mb-3 px-3 text-[10px] font-bold tracking-[.2em] text-blue-300">SCHOOL WORKSPACE</p><nav className="space-y-1.5">{navigation.map(n => <button key={n.page} aria-label={n.label} aria-current={page === n.page ? 'page' : undefined} onClick={() => navigate(n.page)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3.5 text-sm font-semibold transition-colors ${page === n.page ? 'bg-white text-navy shadow-sm' : 'text-blue-100 hover:bg-white/10'}`}><n.icon size={20}/>{n.label}</button>)}</nav><div className="mt-auto pt-8"><button className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm text-blue-200 hover:bg-white/10" onClick={() => open('architecture')}><CircleHelp size={19}/>How the system works</button><div className="mx-2 mt-5 flex items-center gap-3 border-t border-white/10 pt-5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gold text-navy"><GraduationCap size={21}/></span><div><strong className="text-sm">{user.name}</strong><p className="mt-0.5 text-xs text-blue-200">{user.role} · Presentation demo</p></div></div></div></aside>
    <div className="school-main min-h-screen lg:ml-60"><header className="school-header flex min-h-24 flex-wrap items-center justify-between gap-4 border-b border-slate-200 bg-white px-5 py-4 sm:px-8"><div className="flex min-w-0 items-center gap-3"><button className="icon-btn lg:hidden" aria-label="Open navigation" onClick={() => setMobileMenu(true)}><Menu size={23}/></button><Logo className="h-12 w-10 shrink-0 sm:h-14 sm:w-12"/><div><h1 className="text-xl font-bold text-navy sm:text-2xl">Bright Future School</h1><p className="mt-1 text-xs text-slate-500 sm:text-sm">SmartSchool Results Analytics System</p></div></div><div className="flex items-center gap-2"><button className="icon-btn" aria-label={presenting ? 'Exit presentation mode' : 'Presentation mode'} title="Full-screen presentation" onClick={() => void fullScreen()}>{presenting ? <Minimize2 size={20}/> : <Maximize2 size={20}/>}</button><button className="icon-btn" aria-label="Refresh school data" disabled={busy} onClick={refresh}><RefreshCw size={19}/></button><button className="icon-btn" aria-label="Sign out" disabled={busy} onClick={async () => { if (!guard()) return; try { await request('/school/logout', { method: 'POST' }); setUser(null); setData(null); setDialog(null); setDirty(false); } catch (e) { setLoadError(messageOf(e)); } }}><LogOut size={19}/></button></div></header>
    <main className="school-content mx-auto max-w-[1600px] px-5 py-7 sm:px-8">{presenting && <nav className="no-print mb-6 flex flex-wrap gap-2">{navigation.map(n => <button key={n.page} className={page === n.page ? "btn" : "btn-light"} onClick={() => navigate(n.page)}>{n.label}</button>)}</nav>}<div className="page-heading mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold tracking-widest text-slate-400"><span className="h-1.5 w-1.5 rounded-full bg-gold"/>SCHOOL RESULTS</div><h2 className="text-3xl font-bold tracking-tight text-navy">{current.label}</h2><p className="mt-2 text-sm text-slate-500">{current.subtitle}</p></div><span className="flex items-center gap-1.5 text-xs font-medium text-slate-500"><ShieldCheck size={16}/>{busy ? 'Saving changes…' : 'Saved in SQLite'}</span></div>
    {data && <div className="workspace-filters mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-3"><label>Class<select aria-label="Choose class" className="mt-2 w-full" disabled={busy || loading} value={selection.class_id} onChange={e => changeSelection({ ...selection, class_id: Number(e.target.value) })}>{data.classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Session<select aria-label="Choose session" className="mt-2 w-full" disabled={busy || loading} value={selection.session_id} onChange={e => changeSelection({ ...selection, session_id: Number(e.target.value) })}>{data.sessions.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Term<select aria-label="Choose term" className="mt-2 w-full" disabled={busy || loading} value={selection.term} onChange={e => changeSelection({ ...selection, term: e.target.value })}>{data.terms.map(t => <option key={t}>{t}</option>)}</select></label></div>}
    {loadError ? <div className="school-card p-8"><h3 className="text-xl font-bold text-navy">Unable to load school records</h3><ErrorMessage error={loadError}/><button className="btn mt-5" onClick={refresh}>Try again</button></div> : loading || !data ? <div role="status" className="flex min-h-80 items-center justify-center gap-3 text-slate-500"><LoaderCircle size={22} className="animate-spin"/>Loading school results…</div> : <>
      {page === 'dashboard' && <Dashboard data={data} onReport={report} onResults={() => navigate('results')}/>}
      {page === 'students' && <Students key={`${selection.class_id}-${selection.session_id}`} data={data} onAdd={() => { setStudent(undefined); open('student'); }} onEdit={s => { setStudent(s); open('student'); }} onReport={report} onResults={() => navigate('results')}/>}
      {page === 'results' && <Results key={`${data.assessment.id}-${data.assessment.revision}`} data={data} busy={busy} onSave={saveMarks} onEdit={r => { setScoreRow(r); open('scores'); }} onReport={report} onDirty={setDirty}/>}
      {page === 'analytics' && <Analytics data={data} selectedGrade={grade} onGrade={setGrade} onReport={report}/>}
      {page === 'reports' && <>{chosen ? <><div className="no-print mb-5"><label className="max-w-md">Choose a student<select aria-label="Choose a student" className="mt-2 w-full" value={chosen.id} onChange={e => setChosenId(Number(e.target.value))}>{data.results.map(r => <option key={r.id} value={r.id}>{r.name} · {r.student_code}</option>)}</select></label></div><Report key={`${data.assessment.id}-${chosen.id}-${chosen.comment}`} data={data} row={chosen} onEdit={() => { setScoreRow(chosen); open('scores'); }} onComment={async comment => { await perform(`/comments/${chosen.id}?${queryFor(selection)}`, { comment }, 'Teacher comment saved.'); }}/></> : <div className="school-card p-10 text-center text-slate-500">Add students and enter marks to create report sheets.</div>}</>}
      {page === 'settings' && <SchoolSettings key={data.settings.revision} data={data} busy={busy} onSave={async (scale, pass) => { await perform('/settings', { revision: data.settings.revision, scale, pass_mark: pass }, 'Grading rules saved. Results recalculated.'); }} onClass={() => open('class')} onSession={() => open('session')} onArchitecture={() => open('architecture')}/>}
      <footer className="app-foot mt-7 flex flex-wrap items-center justify-between gap-2 border-t border-slate-200 pt-5 text-xs text-slate-400"><span>Bright Future School · Learn. Lead. Excel.</span><span>SmartSchool · Fictional presentation data</span></footer>
    </>}
    </main></div>
    {toast && <div role="status" className="toast-message fixed right-5 bottom-5 z-50 flex max-w-[calc(100vw-40px)] items-center gap-3 rounded-xl border border-emerald-200 bg-white p-4 text-sm text-emerald-800 shadow-lg"><CheckCircle2 size={21} className="shrink-0"/>{toast}<button className="icon-btn" aria-label="Dismiss message" onClick={() => setToast('')}><X size={17}/></button></div>}
    {dialog && <SchoolModal title={dialog === 'student' ? student ? 'Edit student' : 'Add student' : dialog === 'scores' ? 'Enter CA & exam scores' : dialog === 'class' ? 'Add a class' : dialog === 'session' ? 'Add an academic session' : 'Understand the architecture'} onClose={() => setDialog(null)} busy={busy}>
      {dialog === 'student' && data && <StudentForm data={data} student={student} busy={busy} error={formError} onSave={v => void saveStudent(v)} onClose={() => setDialog(null)}/>}
      {dialog === 'scores' && data && scoreRow && <ScoresForm data={data} row={scoreRow} busy={busy} error={formError} onSave={async entry => { try { await saveMarks([entry]); } catch { /* Form displays the error. */ } }} onClose={() => setDialog(null)}/>}
      {dialog === 'class' && <ClassForm busy={busy} error={formError} onSave={async (name, subjects) => { try { const created = await perform('/classes', { name, subjects }, 'Class created.', 'POST'); if (created.id) changeSelection({ ...selection, class_id: created.id }); } catch { /* Form displays the error. */ } }} onClose={() => setDialog(null)}/>}
      {dialog === 'session' && <SessionForm busy={busy} error={formError} onSave={async name => { try { const created = await perform('/sessions', { name }, 'Academic session created.', 'POST'); if (created.id) changeSelection({ ...selection, session_id: created.id }); } catch { /* Form displays the error. */ } }} onClose={() => setDialog(null)}/>}
      {dialog === 'architecture' && <Architecture/>}
      {formError.includes('Refresh') && <button className="mt-4 text-sm font-semibold text-blue-700 underline" onClick={refresh}>Refresh saved records</button>}
    </SchoolModal>}
  </div>;
}
